site_name: "Petshop docs"

theme:
  favicon: assets/logo.png
  name: material
  logo: assets/logo.png
  language: pt
  features:
    - navigation.instant
  palette:
    primary: green
    accent: green

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Reuniões:
    - Reunião 1 - (20/07): reunioes/reuniao1.md
    - Reunião 2 - (27/07): reunioes/reuniao2.md
    - Reunião 3 - (28/07): reunioes/reuniao3.md
  - Manual GhPages: manual.md